package assertions.search;

import models.FieldsItem;

/**
 * {@link FieldsItem} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractFieldsItemAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class FieldsItemAssert extends AbstractFieldsItemAssert<FieldsItemAssert, FieldsItem> {

  /**
   * Creates a new <code>{@link FieldsItemAssert}</code> to make assertions on actual FieldsItem.
   * @param actual the FieldsItem we want to make assertions on.
   */
  public FieldsItemAssert(FieldsItem actual) {
    super(actual, FieldsItemAssert.class);
  }

  /**
   * An entry point for FieldsItemAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myFieldsItem)</code> and get specific assertion with code completion.
   * @param actual the FieldsItem we want to make assertions on.
   * @return a new <code>{@link FieldsItemAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static FieldsItemAssert assertThat(FieldsItem actual) {
    return new FieldsItemAssert(actual);
  }
}
