package assertions.search;

import models.ItemsItem;

/**
 * {@link ItemsItem} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractItemsItemAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ItemsItemAssert extends AbstractItemsItemAssert<ItemsItemAssert, ItemsItem> {

  /**
   * Creates a new <code>{@link ItemsItemAssert}</code> to make assertions on actual ItemsItem.
   * @param actual the ItemsItem we want to make assertions on.
   */
  public ItemsItemAssert(ItemsItem actual) {
    super(actual, ItemsItemAssert.class);
  }

  /**
   * An entry point for ItemsItemAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myItemsItem)</code> and get specific assertion with code completion.
   * @param actual the ItemsItem we want to make assertions on.
   * @return a new <code>{@link ItemsItemAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ItemsItemAssert assertThat(ItemsItem actual) {
    return new ItemsItemAssert(actual);
  }
}
