package assertions.search;

import models.ItemModel;

/**
 * {@link ItemModel} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractItemModelAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ItemModelAssert extends AbstractItemModelAssert<ItemModelAssert, ItemModel> {

  /**
   * Creates a new <code>{@link ItemModelAssert}</code> to make assertions on actual ItemModel.
   * @param actual the ItemModel we want to make assertions on.
   */
  public ItemModelAssert(ItemModel actual) {
    super(actual, ItemModelAssert.class);
  }

  /**
   * An entry point for ItemModelAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myItemModel)</code> and get specific assertion with code completion.
   * @param actual the ItemModel we want to make assertions on.
   * @return a new <code>{@link ItemModelAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ItemModelAssert assertThat(ItemModel actual) {
    return new ItemModelAssert(actual);
  }
}
